// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQNUC_njTQlDPHdBzdGxQbG678_UcMZNg',
    appId: '1:165377489826:android:0316baddcce8b37bf450fb',
    messagingSenderId: '165377489826',
    projectId: 'apnachat-c0e5b',
    storageBucket: 'apnachat-c0e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYX5tiz6rCRyGwvWa6rCtLmd56DpZskPw',
    appId: '1:165377489826:ios:43ee4a97fb88c00ef450fb',
    messagingSenderId: '165377489826',
    projectId: 'apnachat-c0e5b',
    storageBucket: 'apnachat-c0e5b.appspot.com',
    androidClientId: '165377489826-hc1efgke62ajd764bfchktol2ti094lg.apps.googleusercontent.com',
    iosClientId: '165377489826-u46roe6n4pr5eop4gdjrbvieniorcr52.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
